# bitbucket-pipelines.yml - Bitbucket Pipelines configuration.
# Copyright (C) 2016 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
---
image: python:3
pipelines:
  bookmarks:
    "**":
      - step:
          script:
            - python ./setup.py install
